import styles from "../styles/Reddit-api.module.css";
const Reddit = () => {
  return (
    <section className={styles.reddit}>
      <h2>Images generated by Reddit users with Dall-e 2</h2>
      <div className={styles.imgContainer}>
        <div className={styles.card}>
          <img
            src={"./images/image1.webp"}
            alt="universe"
            className={styles.background}
          />
        </div>
      </div>
    </section>
  );
};

export default Reddit;
