import Head from "next/head";
import Navbar from "../components/Navbar";
import Playground from "../components/Playground";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>inspector-ai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Playground />
      <Footer />
    </div>
  );
}
